### ISSUE TITLE
打印中文乱码怎么解决？

### ISSUE THREAD

**Issue by robin1892** [baka397/chn-escpos#3]
打印中文乱码怎么解决？

**Comment by baka397** [comment]
如果是文本乱码,源码在[此处](https://github.com/baka397/chn-escpos/blob/master/lib/printer.js#L37)做了一次针对中文乱码的GBK编码,请确认下传入的text是否有问题.
如果是附带了某些指令的打印内容,请依次测试确认下是否打印机不支持写入的指令

**Comment by Niofh** [comment]
@robin1892 你是怎么链接打印机啊？打印机是固定ip吗？可以通过外网来访问打印机吗？我现在要做一个订餐系统。所以搞不懂怎么打印小票！

**Comment by baka397** [comment]
https://github.com/baka397/chn-escpos/issues/7
