### ISSUE TITLE
开钱箱疑问

### ISSUE THREAD

**Issue by jumkey** [baka397/chn-escpos#5]
'\x1B\x70\x00\xFF\xFF' 是不是需要改成[0x1B,0x70,0x00,0xFF,0xFF]
Buffer.from('\x1B\x70\x00\xFF\xFF').length==7
Buffer.from([0x1B,0x70,0x00,0xFF,0xFF]).length==5
虽然两个都能成功，我觉得初衷应该是发送后者。

**Comment by baka397** [comment]
恩，确实，当时是借鉴的其他语言的16进制命令。
