### ISSUE TITLE
barcode问题

### ISSUE THREAD

**Issue by Hello-Nemo** [baka397/chn-escpos#6]
请问使用code128时的16进制是多少？

**Comment by baka397** [comment]
之前写这个库的时候128我测试的打印机好像没成功过,如果你需要知道的话,可以参考佳博打印机开发手册打印条码部分

**Comment by Hello-Nemo** [comment]
转成图片打印实现的

2017-01-04 18:19 GMT+08:00 bakajinsei <notifications@github.com>:
