### ISSUE TITLE
打印机链接问题

### ISSUE THREAD

**Issue by Niofh** [baka397/chn-escpos#7]
我是刚学没多久node,也不是很懂软件这一块。楼主我想问问我买了佳博的L80160，是通过wifi链接局域网吗？之后node.js怎么链接这个打印机来调用你这个封装好的插件来进行打印。

**Comment by baka397** [comment]
使用windows安装驱动,然后在打印机管理里能够查看和编辑打印机名字,然后使用这个名字进行调用就可以了
