### ISSUE TITLE
我是win10 64位环境，想通过nw.js开发POS系统

### ISSUE THREAD

**Issue by beyondfox** [baka397/chn-escpos#8]
但是我执行npm install chn-escpos后提示错误了
:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: 项目“node_printer.vcxproj”的平台无效。平台为“x64”。您会看到此消息的可能原因是，您尝试在没有解决方案文件
的情况下生成项目，并且为此项目指定了并不存在的非默认平台。 [D:\workspa
ce-frontend\nwjs-sdk\app\v0.0.1\node_modules\printer\build\node_printer.vcxproj]

win10环境是不是编译很复杂，有编译好的吗？多谢！

**Comment by beyondfox** [comment]
如果我用32位的nodejs编译结果就更恐怖了，以下是截取：
c:\users\liujian\.node-gyp\8.4.0\include\node\v8.h(333): error C2988: 不可识别的模板声明/定义 [C:\Program Files (x86)\nodejs\node_
modules\printer\build\node_printer.vcxproj]
c:\users\liujian\.node-gyp\8.4.0\include\node\v8.h(333): error C2059: 语法错误:“using” [C:\Program Files (x86)\nodejs\node_
modules\printer\build\node_printer.vcxproj]
c:\users\liujian\.node-gyp\8.4.0\include\node\v8.h(465): error C2332: “enum”: 缺少标记名 [C:\Program Files (x86)\nodejs\node
_modules\printer\build\node_printer.vcxproj]
c:\users\liujian\.node-gyp\8.4.0\include\node\v8.h(465): error C2236: 意外的“class”“v8::WeakCallbackType”。是否忘记了“;”? [C:\Pr
ogram Files (x86)\nodejs\node_modules\printer\build\node_printer.vcxproj]
c:\users\liujian\.node-gyp\8.4.0\include\node\v8.h(465): error C3381: “v8::WeakCallbackType”: 只有在用 /clr 选项编译的代码中才有程序集访问

可以帮帮我吗？

**Comment by baka397** [comment]
现在这个项目已经停止维护(因为没有打印机测试了),代码仅供参考,以下两部分需要做变更:
1.C部分调用`printer`包,由于8版本C插件的调用方法产生了变化,建议更换另外的包
2.buffer部分采用4版本写法,新版本buffer部分已经被弃用
